name: git-tag-from-changelog
description: Create Git tag from Changelog
author: SlingNode


runs:
  using: node20
  main: dist/index.js


# == inputs and outputs ==

inputs:
  changelog_file:
    required: false
    description: Changelog file name
    default: CHANGELOG.md


outputs:
  latest_repo_git_tag:
    description: Latest tag in the repository
  latest_changelog_git_tag:
    description: Latest tag in the changelog
